import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: " Next My App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav>
          <h6>Logo</h6>
          <ul>
         <li>About</li>
         <li>Service</li>
         <li>Contect</li>
          </ul>
        </nav>
     <div className="h-screen">
     {children}
     </div>
        <footer>
          This is Footer
        </footer>
        </body>
    </html>
  );
}
